# server port config
server:
  port: 8001
  servlet:
   session:
    timeout: 3200
  
# oracle driver config
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##SCON
    password: SCON

# Mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  
